### ISSUE TITLE
Adding "advancedPHP" to your Theme

### ISSUE THREAD

**Issue by dennisosaj** [keisto/Monokai-Pro.novaextension#1]
Heyho,
I saw your theme and noticed a growing popularity.

I'm asking if you could add "advancedPHP" to your theme. It's one of my own extensions and I want to provide more theme coverage for my users.

You can find a theme development documentation in its repo: https://github.com/dennisosaj/advancedphp.novaextension

I would really appreciate it. Thanks!

**Comment by keisto** [comment]
I did add this already. Although I don't use Nova too much for PHP yet, is there something missing? ...scratch that I see you made some new changes to `advancedPHP` 👍. 

I can get that updated later today.

**Comment by dennisosaj** [comment]
Oh wow, that looks awesome. Sorry for bothering you then. Nice job!
