### ISSUE TITLE
JavaScript multiline comments have excessive contrast with their background

### ISSUE THREAD

**Issue by belcar-s** [keisto/Monokai-Pro.novaextension#2]
It seems that JavaScript multiline comments are colored with the javascript.block color. Themes whose background is light have a very dark one, and themes whose background is dark have a very light one.

<img width="537" alt="Screen Shot 2021-06-15 at 16 25 41" src="https://user-images.githubusercontent.com/73370025/122125710-6d0ab800-cdf6-11eb-82a0-e5cebf7d9824.png">

**Comment by keisto** [comment]
Thank you! 😊 I let me know if you have any other issues.
